# config.yaml
controlImage: False
controlPath: "/Users/eliasguan/Desktop/DL_210_data_analysis/testcontrol/control_0h_Incision_Image1_565.tif"
smFISHChannelPath: "/Users/eliasguan/Desktop/DL_210_data_analysis/Example_Image_analysis/smallworm/below_the_eyes/worm1/565/Image1_565.tif"
controlThreshold: null
experimentThreshold: 10
minimal_distance: [2, 2, 2]
kernel_size: [1, 1.7, 1.7]
control_voxel_size: [361, 75, 75]
voxel_size: [361, 75, 75]
spot_size: [600, 300, 300]
decomposition_thresh: [0.7, 1, 5]
min_spots_for_clusters: 4
radius_for_spots: 250
plot_spot_size: 4

# --- Decomposition / Clustering ---
decomposition_thresh: [0.7, 1, 5]
min_spots_for_clusters: 4
radius_for_spots: 250

# --- Plotting / Advanced settings ---
spotsRadiusDetection: false
saveSpotInformation: true
plotInnerCircle: false
plotExactSpot: false
exactSpotSize: 2
plotSpotLabel: false
plot_spot_size: 4
results_folder: results